import { Montserrat } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "@/provider";
import { Toaster } from "sonner";

const montserrat = Montserrat({ subsets: ['latin'] });



export const metadata = {
  title: "Equiskill-AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={montserrat.className}
        >
          <Provider> {children}</Provider>
          <Toaster/>

        </body>
      </html>
    </ClerkProvider>
  );
}
